<?php
// Caution: Run this file only once
require_once 'genericMethods.php'; // Load methods in other file
setup(); // Sets up DB and tables

/**
 * Create DB, add users table and ciphers table, make admin with username "admin" and password "CS174Final"
 */
function setup() {
	echo "Setting up databases and tables ..."."<br>";
	require_once 'login.php';
	buildDB(new mysqli($hn, $un, $pw), $db); // Connect to MySQL and build the database if doesn't exist
	echo "Database '$db' created successfully!"."<br>";
	$conn = new mysqli($hn, $un, $pw, $db); // Create a connection to the database
	echo "Connection to '$db' established!"."<br>";
	buildUsersTable($conn, "Users"); // Build the table of users
	echo "Table 'Users' created successfully!"."<br>";
	insertAdmin($conn, "Users"); // Insert admin into the table of users
	echo "Admin inserted into 'Users'!"."<br>";
	buildCiphersTable($conn, "Ciphers"); // Make the table to store ciphers
	echo "Table 'Ciphers' created successfully!"."<br>";
	echo "Done!"."<br>";
}
// ########## Methods & Helpers ##########
/**
 * Builds database if it doesn't already exist
 */
function buildDB($conn, $name) {
	// Check connection. If cannot connect to MySQL, terminate program. Error not printed (for debugging)
	if ($conn->connect_error) die(mysql_fatal_error("Could not access MySQL when building table: ".$conn->connect_error));
	$sql = "CREATE DATABASE IF NOT EXISTS $name"; // Build database if it does not already exist
	if ($conn->query($sql) === FALSE) echo mysql_fatal_error("Error creating database: ".$conn->error); // Check if database was created successfully
	$conn->close(); // Close the connection
}

/**
 * Builds the table of users
 */
function buildUsersTable($conn, $name) {
	// Check connection. If cannot connect to DB, terminate program. Error not printed (for debugging)
	if ($conn->connect_error) die(mysql_fatal_error("Could not access DB when building table: ".$conn->error));
	// Username: 20 varying chars
	// Password: 60 constant chars
	// Email: 40 varying chars
	$query = "CREATE TABLE IF NOT EXISTS $name (
		Username VARCHAR(20) NOT NULL,
        Password CHAR(60) NOT NULL,
        Email VARCHAR(40) NOT NULL
	)";
	if (! $conn->query($query)) die(mysql_fatal_error("Could not build table: ".$conn->error)); // Error not printed (for debugging)
}

/**
 * Inserts an admin into the table of users
 */
function insertAdmin($conn, $table) {
	/* Admin credentials */
	$username = "admin";
	$password = "CS174Final";
	$email = "admin@admin.com";
	$password = password_hash($password, PASSWORD_BCRYPT); // Randomly salt & hash (60 chars)
	/* Check if admin already exists */
	$query = "SELECT * FROM $table WHERE Username='$username'"; // Query command to execute
	$result = $conn->query($query); // Attempt to retrieve record by executing query command
	if (! $result) die(mysql_fatal_error("Database access failed: ".$conn->error)); // Specific error not printed
	/* Execute below if no DB error */
	$row = $result->fetch_array(MYSQLI_NUM); // Convert it into an associative array
	$result->close(); // Close result
	/* If admin exists, exist */
	if ($row[0] == "admin") return;
	/* Else make admin */
	$query = "INSERT INTO $table VALUES('$username', '$password', '$email')";
	if (! $conn->query($query)) die(mysql_fatal_error("Failed to insert: $query<br>".$conn->error."<br><br>")); // Error is not printed (for debugging)
}
/**
 * Builds a table for users to store input texts, the cipher used,
 * and the timestamp at the moment of the creation of the record.
 */
function buildCiphersTable($conn, $name) {
	/* Check connection. If cannot connect to DB, terminate program. Error not printed (for debugging) */
	if ($conn->connect_error) die(mysql_fatal_error("Could not access DB when building table: ".$conn->error));
	// Username: 20 varying chars (defined above) - stores the owner of the input
	// Cipher: Cipher name can be 20 chars (double transposition is 20 chars)
	// Input: 100 varying chars & not null
	// Output: 100 varying chars & not null
	// Key1: 64 varying chars & not null
	// Key2: 64 varying chars & can be null (required only for double transposition)
	// Timestamp: Automatically generated by MySQL
	$query = "CREATE TABLE IF NOT EXISTS $name (
		id SMALLINT AUTO_INCREMENT NOT NULL,
		Username VARCHAR(20) NOT NULL,
		Cipher VARCHAR(64) NOT NULL,
		Input VARCHAR(100) NOT NULL,
		Output VARCHAR(100) NOT NULL,
		Key1 VARCHAR(64) NOT NULL,
		Key2 VARCHAR(64),
		Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		PRIMARY KEY (id)
	)";
	if (! $conn->query($query)) die(mysql_fatal_error("Could not build table: ".$conn->error));
}